pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/sdk:8.0'
            //image 'mcr.microsoft.com/dotnet/sdk:9.0'
            // no args here — run as default non-root
        }
    }

    environment {
        DOTNET_CLI_HOME = "${env.WORKSPACE}/.dotnet"
        DOTNET_CLI_TELEMETRY_OPTOUT = '1'
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "1"
    }

    stages {
        // stage('Clean Workspace') {
        //     steps {
        //         deleteDir()
        //     }
        // }

        // stage('Checkout'){
        //     steps {
        //         checkout scm
        //     }
        // }

        stage('Build') {
            steps {
                //sh 'chmod +x cicd/deb-publish.sh'
                sh 'dotnet --info'
                sh 'dotnet restore --disable-parallel'
                sh './cicd/deb-publish.sh'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'release/*.deb', onlyIfSuccessful: true
            }
        }
    }
}